### ISSUE TITLE
Add client example

### ISSUE THREAD

**Issue by Jonathan-Landeed** [connectrpc/authn-go#20]
A client example of best practices would be good. I assume we're supposed to use an interceptor to add auth headers, but right now the only interceptor example in the connectrpc docs is using `req.Spec().IsClient` magic. This project just moves the server-side portion of the interceptor to middleware to avoid unauthenticated resource usage, correct?

**Comment by emcfarlane** [comment]
Hi @Jonathan-Landeed, yes thats correct. To avoid unmarshalling messages and any extra work the authnetication is done above the connectrpc handler layer. There are some API changes being worked on (see #9) but will update the examples when these land. The best place to see usage is in the godocs https://pkg.go.dev/connectrpc.com/authn#example-package-BasicAuth
