### ISSUE TITLE
unable to create Requests

### ISSUE THREAD

**Issue by terinjokes** [connectrpc/authn-go#8]
I would like to test my implementation of `AuthFunc` in isolation, however the parameters to the function include a lightweight wrapper around `http.Request` where the request field is not exported nor a constructor function provided. This makes it much more complicated to test an `AuthFunc` as instead of being able to call it directly in test, I must wrap it in the middleware and implement another `http.Handler` to thread the Info back to my test function.

Can the request field be exported, or a constructor function for `authn.Request` be created?

---

I would like to be able to do something like:

```golang
func TestAuthFunc(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/", http.NoBody)
	req.Header.Set("Authorization", "Basic YWxhZGRpbjpvcGVuc2VzYW1l")

	info, err := MyAuthFunc(context.Background(), authn.Request{req})
	if err != nil {
		t.Fatalf("unexpected error from AuthFunc: %w", err)
	}

	if username, ok := info.(string); !ok {
		t.Fatalf("info was not string")
	} else if username != "aladdin" {
		t.Fatalf("unexpected username: %s", username)
	}
}
```

---

Right now I have to do something similar to this, which is significantly less clear what is under test.

```golang

func TestAuthFunc(t *testing.T) {
	mw := authn.NewMiddleware(MyAuthFunc)

	req := httptest.NewRequest(http.MethodGet, "/", http.NoBody)
	req.Header.Set("Authorization", "Basic YWxhZGRpbjpvcGVuc2VzYW1l")
	resp := httptest.NewRecorder()

	infoCh := make(chan string, 1)
	h := mw.Wrap(http.HandlerFunc(func(w *http.ResponseWriter, r http.Request) {
		info, ok := authn.GetInfo(r.Context()).(string)
		if !ok {
			close(infoCh)
			w.WriteHeader(http.StatusForbidden)
			return
		}

		infoCh <- info
	}))

	h.ServeHTTP(rec, resp)
	if rec.Code != 200 {
		t.Fatalf("unexpected status code: %s", rec.Code)
	}

	info := <-infoCh
	if info != "aladdin" {
		t.Fatalf("unexpected username: %s", username)
	}
}
```

I also believe this example test has a channel bug, but I'm going to stop working on the example now. The real one became significantly more complex as a result of not being able to directly test outputs to inputs.

**Comment by emcfarlane** [comment]
Hey @terinjokes, thanks for using the library and raising the issue. I've raised a PR to export the constructor.
